iot-mqtt-mvc/IoTProjekt/Models/ErrorViewModel.cs
using System;

namespace IoTProjekt.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

iot-mqtt-mvc/IoTProjekt/Models/Motion.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace IoTProjekt.Models
{
    public class Motion
    {
        [Key]
        public int Id { get; set; }

        [Required]
        public bool Value { get; set; }

        public DateTime InsertedAt { get; set; }
    }
}

iot-mqtt-mvc/IoTProjekt/Controllers/HomeController.cs
using IoTProjekt.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace IoTProjekt.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

iot-mqtt-mvc/IoTProjekt/Controllers/MotionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using IoTProjekt.Data;
using IoTProjekt.Models;

namespace IoTProjekt
{
    public class MotionsController : Controller
    {
        private readonly IoTProjektContext _context;

        public MotionsController(IoTProjektContext context)
        {
            _context = context;
        }

        // GET: Motions
        public async Task<IActionResult> Index()
        {
            return View(await _context.Motion.ToListAsync());
        }

        // GET: Motions/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var motion = await _context.Motion
                .FirstOrDefaultAsync(m => m.Id == id);
            if (motion == null)
            {
                return NotFound();
            }

            return View(motion);
        }

        // GET: Motions/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Motions/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Value,InsertedAt")] Motion motion)
        {
            if (ModelState.IsValid)
            {
                _context.Add(motion);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(motion);
        }

        // GET: Motions/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var motion = await _context.Motion.FindAsync(id);
            if (motion == null)
            {
                return NotFound();
            }
            return View(motion);
        }

        // POST: Motions/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Value,InsertedAt")] Motion motion)
        {
            if (id != motion.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(motion);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MotionExists(motion.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(motion);
        }

        // GET: Motions/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var motion = await _context.Motion
                .FirstOrDefaultAsync(m => m.Id == id);
            if (motion == null)
            {
                return NotFound();
            }

            return View(motion);
        }

        // POST: Motions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var motion = await _context.Motion.FindAsync(id);
            _context.Motion.Remove(motion);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MotionExists(int id)
        {
            return _context.Motion.Any(e => e.Id == id);
        }
    }
}

iot-mqtt-mvc/IoTProjekt/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<script>
    function controlOn() {
        $.get("http://localhost:8080/asitek/control/on");
        $('#status').html('uključeno');
    }

    function controlOff() {
        $.get("http://localhost:8080/asitek/control/off");
        $('#status').html('isključeno');
    }
</script>

<div class="text-center">
    <h1 class="display-4">Upravljanje</h1>

    <div class="container">
        <div class="row">
            <div class="col-sm">
                <button type="button" class="btn btn-success" onclick="controlOn()">Uključi</button>
            </div>
            <div class="col-sm">
                <button type="button" class="btn btn-danger" onclick="controlOff()">Isključi</button>
            </div>
        </div>

        <div class="row">
            <div class="col-sm">
                Trenutno stanje: <div id="status"></div>
            </div>
        </div>
    </div>
</div>

iot-mqtt-mvc/IoTProjekt/Views/Motions/Create.cshtml
@model IoTProjekt.Models.Motion

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Motion</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Value" /> @Html.DisplayNameFor(model => model.Value)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="InsertedAt" class="control-label"></label>
                <input asp-for="InsertedAt" class="form-control" />
                <span asp-validation-for="InsertedAt" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

iot-mqtt-mvc/IoTProjekt/Views/Motions/Delete.cshtml
@model IoTProjekt.Models.Motion

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Motion</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Value)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Value)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.InsertedAt)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.InsertedAt)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

iot-mqtt-mvc/IoTProjekt/Views/Motions/Details.cshtml
@model IoTProjekt.Models.Motion

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Motion</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Value)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Value)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.InsertedAt)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.InsertedAt)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

iot-mqtt-mvc/IoTProjekt/Views/Motions/Edit.cshtml
@model IoTProjekt.Models.Motion

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Motion</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Value" /> @Html.DisplayNameFor(model => model.Value)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="InsertedAt" class="control-label"></label>
                <input asp-for="InsertedAt" class="form-control" />
                <span asp-validation-for="InsertedAt" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

iot-mqtt-mvc/IoTProjekt/Views/Motions/Index.cshtml
@model IEnumerable<IoTProjekt.Models.Motion>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Value)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.InsertedAt)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Value)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.InsertedAt)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

iot-mqtt-mvc/IoTProjekt/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - IoTProjekt</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">IoTProjekt</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Motions" asp-action="">Motions</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - IoTProjekt - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>